{"name": "test_login_success_c", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1", "trace": "self = <studyPython.com.chapter07.lesson10.test_feature_story.TestLogin object at 0x0000022772BAF9A0>\n\n    @allure.story(\"密码缺失\")\n    def test_login_success_c(self):\n        with allure.step(\"点击用户名\"):\n            print(\"输入用户名\")\n        with allure.step(\"点击密码\"):\n            print(\"输入密码\")\n        print(\"点击登录\")\n        with allure.step(\"点击登录之后登录失败\"):\n>           assert '1' == 1\nE           AssertionError: assert '1' == 1\n\ntest_feature_story.py:31: AssertionError"}, "steps": [{"name": "点击用户名", "status": "passed", "start": 1657761365419, "stop": 1657761365419}, {"name": "点击密码", "status": "passed", "start": 1657761365419, "stop": 1657761365419}, {"name": "点击登录之后登录失败", "status": "failed", "statusDetails": {"message": "AssertionError: assert '1' == 1\n", "trace": "  File \"D:\\Environment\\MyPythonStudy\\studyPython\\com\\chapter07\\lesson10\\test_feature_story.py\", line 31, in test_login_success_c\n    assert '1' == 1\n"}, "start": 1657761365419, "stop": 1657761365419}], "attachments": [{"name": "stdout", "source": "bd4dc6a2-236c-4d83-a62a-6ec2c440b62c-attachment.txt", "type": "text/plain"}], "start": 1657761365419, "stop": 1657761365419, "uuid": "d3818226-f828-4959-bec4-e896bcd340cd", "historyId": "585c93ad9da0dc70282a31cabd63680d", "testCaseId": "61a2eb04f7fbe2b862b12b8d4ff1de62", "fullName": "test_feature_story.TestLogin#test_login_success_c", "labels": [{"name": "feature", "value": "登录"}, {"name": "story", "value": "密码缺失"}, {"name": "suite", "value": "test_feature_story"}, {"name": "subSuite", "value": "TestLogin"}, {"name": "host", "value": "tonghuan"}, {"name": "thread", "value": "3964-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_feature_story"}]}